//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBooks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string Book_Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
    }
}
